### ISSUE TITLE
Accumulation of Cross-Sections - OSU Calculus 2

### ISSUE THREAD

**Issue by perryand** [mooculus/calculus2#1]
In the first explanation, in the last answer box, I know the answer is (1/3)(g^3).  I checked this answer with the textbook, but no matter how I write it, the homework will not except that answer.

**Comment by bartsnapp** [comment]
This is a bug - I've fixed it an attempted to redeploy.

The issue is that $\answer[given]{\frac{1}{3}g^3}$ is not validating as g^3/3

**Comment by StevenGubkin** [comment]
This is disturbing.  We really need to check how the parser is working with
fractions.

**Comment by kisonecat** [comment]
https://github.com/kisonecat/math-expressions/commit/0294f5999f45dad8f7a5dd951d7b97f44b9c80d5 fixes this bug in the expression parser.

I'll redeploy ximera.
