### ISSUE TITLE
Validator error: Accumulation of Cross-Sections

### ISSUE THREAD

**Issue by bartsnapp** [mooculus/calculus2#3]
In Accumulation of Cross-Sections

\[
A(x) = \answer[given]{\pi \left(\frac{x}{2}\right)^2}
\]

cannot be answered correctly.

**Comment by StevenGubkin** [comment]
Are \left and \right in the parser?

**Comment by kisonecat** [comment]
It turns out that somewhere in our plumbing `\left(` becomes `\left (`.  The former gets parsed correctly; the latter does not.

https://github.com/kisonecat/math-expressions/commit/b8bcb13993d0ddbc3292e09a849a086634f39eb4 has a test exhibiting the bug and a fix; I'm redeploying Ximera with it now.
