### ISSUE TITLE
Parametric Equations Examples 2 and 3

### ISSUE THREAD

**Issue by perryand** [mooculus/calculus2#9]
Example 2 won't accept -4((y+1)/3)^2 as the correct answer. Example 3 won't accept (x/-5)^3 as the answer.  I did check the book to make sure they are the correct answers.

**Comment by hczhcz** [comment]
Your answers are the same as the answer given on LaTeX documents.
Try refresh the webpage (Ctrl+F5) and it probably works :)

**Comment by bartsnapp** [comment]
That's right - try a "hard refresh"

https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.VwZuLyCgqV4
